/**
 * React Project Exporter - Génère un projet React complet exportable
 */

import JSZip from 'jszip'
import { saveAs } from 'file-saver'

export interface ReactProjectOptions {
  projectName: string
  code: string
  description?: string
  author?: string
}

export class ReactProjectExporter {
  /**
   * Génère et télécharge un projet React complet
   */
  async exportProject(options: ReactProjectOptions): Promise<void> {
    const zip = new JSZip()
    const projectName = this.sanitizeProjectName(options.projectName)

    // Structure de base
    const root = zip.folder(projectName)!

    // package.json
    root.file('package.json', this.generatePackageJson(options))

    // tsconfig.json
    root.file('tsconfig.json', this.generateTsConfig())

    // vite.config.ts
    root.file('vite.config.ts', this.generateViteConfig())

    // index.html
    root.file('index.html', this.generateIndexHtml(options))

    // README.md
    root.file('README.md', this.generateReadme(options))

    // .gitignore
    root.file('.gitignore', this.generateGitignore())

    // src/
    const src = root.folder('src')!
    
    // src/main.tsx
    src.file('main.tsx', this.generateMainTsx())

    // src/App.tsx (code généré)
    src.file('App.tsx', this.generateAppTsx(options.code))

    // src/index.css
    src.file('index.css', this.generateIndexCss())

    // src/vite-env.d.ts
    src.file('vite-env.d.ts', this.generateViteEnv())

    // public/
    const publicFolder = root.folder('public')!
    publicFolder.file('.gitkeep', '')

    // Générer le ZIP et télécharger
    const blob = await zip.generateAsync({ type: 'blob' })
    saveAs(blob, `${projectName}.zip`)
  }

  /**
   * Sanitize project name
   */
  private sanitizeProjectName(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      || 'my-react-app'
  }

  /**
   * Génère package.json
   */
  private generatePackageJson(options: ReactProjectOptions): string {
    return JSON.stringify({
      name: this.sanitizeProjectName(options.projectName),
      private: true,
      version: '0.1.0',
      type: 'module',
      description: options.description || 'React application generated by CodeCraft Studio',
      author: options.author || 'CodeCraft Studio',
      scripts: {
        dev: 'vite',
        build: 'tsc && vite build',
        preview: 'vite preview',
        lint: 'eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0'
      },
      dependencies: {
        react: '^18.2.0',
        'react-dom': '^18.2.0'
      },
      devDependencies: {
        '@types/react': '^18.2.43',
        '@types/react-dom': '^18.2.17',
        '@typescript-eslint/eslint-plugin': '^6.14.0',
        '@typescript-eslint/parser': '^6.14.0',
        '@vitejs/plugin-react': '^4.2.1',
        eslint: '^8.55.0',
        'eslint-plugin-react-hooks': '^4.6.0',
        'eslint-plugin-react-refresh': '^0.4.5',
        typescript: '^5.2.2',
        vite: '^5.0.8'
      }
    }, null, 2)
  }

  /**
   * Génère tsconfig.json
   */
  private generateTsConfig(): string {
    return JSON.stringify({
      compilerOptions: {
        target: 'ES2020',
        useDefineForClassFields: true,
        lib: ['ES2020', 'DOM', 'DOM.Iterable'],
        module: 'ESNext',
        skipLibCheck: true,
        moduleResolution: 'bundler',
        allowImportingTsExtensions: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        jsx: 'react-jsx',
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true
      },
      include: ['src'],
      references: [{ path: './tsconfig.node.json' }]
    }, null, 2)
  }

  /**
   * Génère vite.config.ts
   */
  private generateViteConfig(): string {
    return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
    open: true
  },
  build: {
    outDir: 'dist',
    sourcemap: true
  }
})
`
  }

  /**
   * Génère index.html
   */
  private generateIndexHtml(options: ReactProjectOptions): string {
    return `<!doctype html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${options.projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
  }

  /**
   * Génère README.md
   */
  private generateReadme(options: ReactProjectOptions): string {
    const projectName = this.sanitizeProjectName(options.projectName)
    return `# ${options.projectName}

${options.description || 'Application React générée par CodeCraft Studio'}

## 🚀 Démarrage rapide

### Installation des dépendances
\`\`\`bash
npm install
\`\`\`

### Développement local
\`\`\`bash
npm run dev
\`\`\`

L'application sera accessible sur [http://localhost:3000](http://localhost:3000)

### Build production
\`\`\`bash
npm run build
\`\`\`

Les fichiers de production seront générés dans le dossier \`dist/\`

### Preview du build
\`\`\`bash
npm run preview
\`\`\`

## 📦 Stack technique

- **React 18** - Library UI
- **TypeScript** - Typage statique
- **Vite** - Build tool ultra-rapide
- **ESLint** - Linting

## 🎨 Structure du projet

\`\`\`
${projectName}/
├── public/          # Assets statiques
├── src/
│   ├── App.tsx      # Composant principal
│   ├── main.tsx     # Point d'entrée
│   └── index.css    # Styles globaux
├── index.html       # Template HTML
├── package.json     # Dépendances
├── tsconfig.json    # Config TypeScript
└── vite.config.ts   # Config Vite
\`\`\`

## 📝 Scripts disponibles

- \`npm run dev\` - Démarre le serveur de développement
- \`npm run build\` - Build pour production
- \`npm run preview\` - Preview du build production
- \`npm run lint\` - Vérifie le code avec ESLint

## 🚀 Déploiement

### Vercel
\`\`\`bash
npm install -g vercel
vercel
\`\`\`

### Netlify
\`\`\`bash
npm install -g netlify-cli
netlify deploy --prod
\`\`\`

### Cloudflare Pages
\`\`\`bash
npm run build
npx wrangler pages deploy dist
\`\`\`

---

**Généré avec ❤️ par [CodeCraft Studio](https://codecraft.studio)**
`
  }

  /**
   * Génère .gitignore
   */
  private generateGitignore(): string {
    return `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

node_modules
dist
dist-ssr
*.local

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
`
  }

  /**
   * Génère src/main.tsx
   */
  private generateMainTsx(): string {
    return `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`
  }

  /**
   * Génère src/App.tsx à partir du code généré
   */
  private generateAppTsx(generatedCode: string): string {
    // Si le code contient déjà un export, on l'utilise tel quel
    if (generatedCode.includes('export default')) {
      return generatedCode
    }

    // Sinon, on wrap le code dans un composant React
    return `import { useState } from 'react'

function App() {
  return (
    <>
      ${generatedCode}
    </>
  )
}

export default App
`
  }

  /**
   * Génère src/index.css
   */
  private generateIndexCss(): string {
    return `:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;

  color-scheme: light dark;
  color: rgba(255, 255, 255, 0.87);
  background-color: #242424;

  font-synthesis: none;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

a {
  font-weight: 500;
  color: #646cff;
  text-decoration: inherit;
}
a:hover {
  color: #535bf2;
}

body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
}

h1 {
  font-size: 3.2em;
  line-height: 1.1;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #1a1a1a;
  cursor: pointer;
  transition: border-color 0.25s;
}
button:hover {
  border-color: #646cff;
}
button:focus,
button:focus-visible {
  outline: 4px auto -webkit-focus-ring-color;
}

@media (prefers-color-scheme: light) {
  :root {
    color: #213547;
    background-color: #ffffff;
  }
  a:hover {
    color: #747bff;
  }
  button {
    background-color: #f9f9f9;
  }
}
`
  }

  /**
   * Génère src/vite-env.d.ts
   */
  private generateViteEnv(): string {
    return `/// <reference types="vite/client" />
`
  }
}
