import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import { extractSeparatedCode } from './codeExtractor'
import type { FileItem } from '../contexts/AppContext'

/**
 * Export single HTML file
 */
export function exportHTML(code: string, filename: string = 'index.html') {
  const blob = new Blob([code], { type: 'text/html;charset=utf-8' })
  saveAs(blob, filename)
}

/**
 * Export separated HTML/CSS/JS as ZIP
 */
export async function exportSeparatedZIP(code: string) {
  const { html, css, js } = extractSeparatedCode(code)
  
  const zip = new JSZip()
  zip.file('index.html', html)
  
  if (css) {
    zip.file('style.css', css)
  }
  
  if (js) {
    zip.file('script.js', js)
  }
  
  const blob = await zip.generateAsync({ type: 'blob' })
  saveAs(blob, 'project-separated.zip')
}

/**
 * Export full project with all files as ZIP
 */
export async function exportProjectZIP(files: FileItem[]) {
  const zip = new JSZip()
  
  // Add all files
  files.forEach(file => {
    zip.file(file.name, file.content)
  })
  
  // Add README
  const readme = `# CodeCraft Studio Project

## Files
${files.map(f => `- ${f.name}`).join('\n')}

## How to Run
1. Extract this ZIP file
2. Open index.html in your browser
3. Or use a local server: \`npx serve .\`

## Generated by
CodeCraft Studio - https://codecraft.studio

## Date
${new Date().toISOString()}
`
  
  zip.file('README.md', readme)
  
  // Add package.json
  const packageJson = {
    name: 'codecraft-project',
    version: '1.0.0',
    description: 'Project generated by CodeCraft Studio',
    scripts: {
      start: 'serve .',
      dev: 'serve .'
    }
  }
  
  zip.file('package.json', JSON.stringify(packageJson, null, 2))
  
  const blob = await zip.generateAsync({ 
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: {
      level: 6
    }
  })
  
  saveAs(blob, 'codecraft-project.zip')
}

/**
 * Copy code to clipboard
 */
export async function copyToClipboard(code: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(code)
    return true
  } catch (err) {
    console.error('Failed to copy:', err)
    return false
  }
}
